export const catogories = [
  "Cardiologist",
  "Dermatologist",
  "Endocrinologist",
  "Gastroenterologist",
  "General Practitioner",
  "Gynecologist",
  "Hematologist",
  "Neurologist",
  "Oncologist",
  "Ophthalmologist",
  "Orthopedic Surgeon",
  "Otolaryngologist (ENT)",
  "Pediatrician",
  "Psychiatrist",
  "Pulmonologist",
  "Radiologist",
  "Rheumatologist",
  "Urologist",
  "Dentist",
  "Dermatologic Surgeon",
  "Allergist/Immunologist",
  "Nephrologist",
  "Infectious Disease Specialist",
  "Anesthesiologist",
  "Podiatrist",
  "Physical Therapist",
  "Plastic Surgeon",
  "Geriatrician",
  "Chiropractor",
  "Sleep Specialist",
  "Obstetrician",
  "Emergency Medicine Specialist",
];

export const doctors = [
  {
    name: "Dr. Ayesha Khan",
    appointmentTime: "10:00 AM - 2:00 PM",
    fees: 1500,
    category: "Cardiologist",
    hospital: "Aga Khan University Hospital, Karachi",
    gender: "Female",
  },
  {
    name: "Dr. Hassan Ahmed",
    appointmentTime: "1:00 PM - 5:00 PM",
    fees: 2000,
    category: "Dermatologist",
    hospital: "Shaukat Khanum Memorial Hospital, Lahore",
    gender: "Male",
  },
  {
    name: "Dr. Sara Iqbal",
    appointmentTime: "9:00 AM - 12:00 PM",
    fees: 1200,
    category: "Pediatrician",
    hospital: "Punjab Institute of Cardiology, Lahore",
    gender: "Female",
  },
  {
    name: "Dr. Imran Ali",
    appointmentTime: "11:00 AM - 3:00 PM",
    fees: 1800,
    category: "Neurologist",
    hospital: "Holy Family Hospital, Rawalpindi",
    gender: "Male",
  },
  {
    name: "Dr. Farah Yasmeen",
    appointmentTime: "2:00 PM - 6:00 PM",
    fees: 2500,
    category: "Gynecologist",
    hospital: "Jinnah Postgraduate Medical Centre, Karachi",
    gender: "Female",
  },
  {
    name: "Dr. Zeeshan Qureshi",
    appointmentTime: "10:00 AM - 4:00 PM",
    fees: 1600,
    category: "Orthopedic Surgeon",
    hospital: "Indus Hospital, Karachi",
    gender: "Male",
  },
  {
    name: "Dr. Nadia Khan",
    appointmentTime: "8:00 AM - 12:00 PM",
    fees: 1400,
    category: "Endocrinologist",
    hospital: "PIMS Hospital, Islamabad",
    gender: "Female",
  },
  {
    name: "Dr. Faisal Sheikh",
    appointmentTime: "3:00 PM - 7:00 PM",
    fees: 2200,
    category: "Pulmonologist",
    hospital: "Civil Hospital, Karachi",
    gender: "Male",
  },
  {
    name: "Dr. Rabia Zafar",
    appointmentTime: "12:00 PM - 4:00 PM",
    fees: 2000,
    category: "Psychiatrist",
    hospital: "Liaquat National Hospital, Karachi",
    gender: "Female",
  },
  {
    name: "Dr. Arif Malik",
    appointmentTime: "9:00 AM - 1:00 PM",
    fees: 1300,
    category: "Gastroenterologist",
    hospital: "Mayo Hospital, Lahore",
    gender: "Male",
  },
  {
    name: "Dr. Mahnoor Akhtar",
    appointmentTime: "2:00 PM - 6:00 PM",
    fees: 1700,
    category: "Ophthalmologist",
    hospital: "Lady Reading Hospital, Peshawar",
    gender: "Female",
  },
  {
    name: "Dr. Bilal Chaudhry",
    appointmentTime: "11:00 AM - 3:00 PM",
    fees: 1900,
    category: "Radiologist",
    hospital: "Sheikh Zayed Hospital, Lahore",
    gender: "Male",
  },
  {
    name: "Dr. Khalid Aslam",
    appointmentTime: "10:00 AM - 2:00 PM",
    fees: 2300,
    category: "Urologist",
    hospital: "Quaid-e-Azam International Hospital, Islamabad",
    gender: "Male",
  },
  {
    name: "Dr. Zara Mahmood",
    appointmentTime: "3:00 PM - 7:00 PM",
    fees: 1500,
    category: "Allergist",
    hospital: "Medicare Cardiac & General Hospital, Karachi",
    gender: "Female",
  },
  {
    name: "Dr. Usman Raza",
    appointmentTime: "9:00 AM - 1:00 PM",
    fees: 2100,
    category: "Dentist",
    hospital: "Fatima Memorial Hospital, Lahore",
    gender: "Male",
  },
  {
    name: "Dr. Noor Fatima",
    appointmentTime: "8:00 AM - 12:00 PM",
    fees: 1600,
    category: "Geriatrician",
    hospital: "Abbasi Shaheed Hospital, Karachi",
    gender: "Female",
  },
  {
    name: "Dr. Ahmed Rehman",
    appointmentTime: "1:00 PM - 5:00 PM",
    fees: 1800,
    category: "Nephrologist",
    hospital: "Sindh Institute of Urology and Transplantation, Karachi",
    gender: "Male",
  },
  {
    name: "Dr. Asma Tariq",
    appointmentTime: "10:00 AM - 2:00 PM",
    fees: 1400,
    category: "ENT Specialist",
    hospital: "Holy Family Hospital, Rawalpindi",
    gender: "Female",
  },
  {
    name: "Dr. Kamran Siddiqui",
    appointmentTime: "3:00 PM - 7:00 PM",
    fees: 2000,
    category: "Oncologist",
    hospital: "Pakistan Institute of Medical Sciences, Islamabad",
    gender: "Male",
  },
  {
    name: "Dr. Sana Aziz",
    appointmentTime: "12:00 PM - 4:00 PM",
    fees: 1700,
    category: "Physiotherapist",
    hospital: "Rehmat Medical Centre, Lahore",
    gender: "Female",
  },
];
